splash = false

wallpaper{
    monitor=DP-2
    path=/home/forlnx/Imagens/Wallpapers/mont-blanc.jpg
    fit_mode=cover
}

wallpaper{
    monitor = HDMI-A-2
    path = /home/forlnx/Imagens/Wallpapers/beautiful-sky-landscape-silhouette-moon.jpg
    fit_mode = cover
}
