# Diretório Base XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# Detectar SO
if [[ "$(uname)" == "Darwin" ]]; then
  export OS_TYPE="macos"
else
  export OS_TYPE="linux"
fi